version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: 'teste123'
      POSTGRES_USER: 'teste'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432
    container_name: database-p4

  api:
    image: hallzero/express-p4:latest
    restart: always
    environment:
      DB_HOST: db
      DB_USER: teste
      DB_PASS: teste123
      DB_NAME: postgres
    ports:
      - 3000:3000
    depends_on:
      - db
    container_name: api-p4

  python:
    image: hallzero/python-p4:latest
    restart: always
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./machine-learning:/app/machine-learning
    container_name: python-p4
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
